version: "3"

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/app
      - ./nginx/main.conf:/etc/nginx/conf.d/default.conf
    container_name: "nginx"
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./app:/var/www/app
    container_name: "php"

    environment:
      XDEBUG_MODE: coverage
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003

    depends_on:
      mysql:
        condition: service_healthy
    


  mysql:
    image: mysql:latest
    command: mysqld --sql_mode="" --default_authentication_plugin=mysql_native_password
    restart: always
    ports:
      - 4001:3306

    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: qwerty

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    

    

  
  adminer:
    image: adminer
    restart: always
    container_name: "adminer"

    ports:
      - 4002:8080


