version: "3"

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/app
      - ./nginx/main.conf:/etc/nginx/conf.d/default.conf
    container_name: "nginx"
    depends_on:
      - php

  php:
    build: ./php
    restart: always
    volumes:
      - ./app:/var/www/app
    container_name: "app"


  mysql:
    image: mysql:latest
    command: mysqld --sql_mode="" --default_authentication_plugin=mysql_native_password
    restart: always
    ports:
      - 4001:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

    container_name: "app_mysql"
  
  adminer:
    image: adminer
    restart: always
    container_name: "adminer"

    ports:
      - 4002:8080


